### ISSUE TITLE
Add an annotation for defining a scope for the generated CSS rules

### ISSUE THREAD

**Issue by janScheible** [janScheible/knorxx#7]
``` java
@StyleScope(".myApplication")
public class Appearance extends CssDefinition {
    String HEADING_STYLE = build(Properties.builder()
            .setBackground(convertColor(DEFAULT_COLOR))
            .setColor(convertColor(Color.WHITE)));
}
```

This should still lead to the corresponding generated JavaScript for referencing the rule:

``` javascript
Appearance.HEADING_STYLE = 'headingStyle';
```

But to an additional selector for the generated CSS rules:

``` css
.myApplication .headingStyle {
    background-color: #ff0000;
    color: #ffffff;
}
```
